/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2025-08-04 09:50:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class warehouse_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/admin/footer.jsp", Long.valueOf(1751597016037L));
    _jspx_dependants.put("/admin/header.jsp", Long.valueOf(1753027783801L));
    _jspx_dependants.put("jar:file:/C:/Users/n21dc/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Users/n21dc/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
    _jspx_dependants.put("jar:file:/C:/Users/n21dc/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Stock Check</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "pagehead.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "pageLoad.jsp", out, false);
      out.write("\r\n");
      out.write("    <link href=\"../css/warehouse-style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/custom_background_template.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/custom_row_template.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/table_list_admin_template.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/search_button_template.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/custom_border_template.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"body\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/search_button_template.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/custom_background_template.css\"/>\r\n");
      out.write("\r\n");
      out.write("<div class=\"background-div-header\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/\">\r\n");
      out.write("								<img src=\"../images/Privacy_private_security-512.png\" class=\"logo-size\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							<h1>\r\n");
      out.write("								<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/\" class=\"text-dark\" style=\"text-decoration: none\">\r\n");
      out.write("									The Shirt Store Administration\r\n");
      out.write("								</a>\r\n");
      out.write("							</h1>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col justify-content-end align-self-center text-end\">\r\n");
      out.write("				<h3 class=\"mb-0 me-3\">\r\n");
      out.write("					Hi there, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userFullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					<a href=\"logout\" class=\"btn custom-btn-cart fs-5 ms-2\">Logout</a>\r\n");
      out.write("				</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Start of logo rows -->\r\n");
      out.write("		<div class=\"container text-center\">\r\n");
      out.write("			<div class=\"row justify-content-start mb-3\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_category\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/app.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Category</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_attributes\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/app.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Attribute</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_tags\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/app.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Tag</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_products\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/shirt.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Products</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_product_variants\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/service.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Variants</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row justify-content-start mb-3\">\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_rates\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/Rate.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Rate</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_orders\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/shopping-cart.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Order</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_warehouses\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/warehouse.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Warehouse</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"chat\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/messenger.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Messenger</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"list_customer\" class=\"btn custom-btn-admin-header\">\r\n");
      out.write("						<img src=\"../images/service.png\" class=\"logo-size\">\r\n");
      out.write("						<div class=\"mt-2\">Customer</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End of logo rows -->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"background-div-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"w-layout-blockcontainer container w-container\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"nav-wrapper\">\r\n");
      out.write("                    <h1 class=\"heading-h1\">Warehouse</h1>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"nav-button-wrapper\">\r\n");
      out.write("                        <a href=\"list_imports\" class=\"button w-button\">View Import Receipt</a>\r\n");
      out.write("                        <a href=\"show_import_form\" class=\"button w-button\">Create Import Receipt</a>\r\n");
      out.write("                        <a href=\"list_warehouses\" class=\"button w-button\">Stock Check</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h1 class=\"heading-h2\">Stock Check</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"search-wrapper\">\r\n");
      out.write("                    <form action=\"stock_check_search\" class=\"search w-form\">\r\n");
      out.write("                        <input class=\"search-input w-input\" maxlength=\"256\"\r\n");
      out.write("                               name=\"query\" placeholder=\"Search…\" type=\"search\" id=\"search\" required=\"\" />\r\n");
      out.write("                        <input type=\"submit\"\r\n");
      out.write("                               class=\"button is-medium-button w-button\" value=\"Search\" />\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <table class=\"table-wrapper\">\r\n");
      out.write("                    <thead class=\"table_head\">\r\n");
      out.write("                    <tr class=\"table_row\">\r\n");
      out.write("                        <th class=\"table_header align-middle text-center\">Product&#x27;s ID</th>\r\n");
      out.write("                        <th class=\"table_header align-middle text-center\">Product&#x27;s Name</th>\r\n");
      out.write("                        <th class=\"table_header align-middle text-center\">Quantity</th>\r\n");
      out.write("                        <th class=\"table_header align-middle text-center\">Updated Date</th>\r\n");
      out.write("                        <th class=\"table_header align-middle text-center\">Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody class=\"table_body\" id=\"tableBody\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row justify-content-center mb-5\">\r\n");
      out.write("                    <div class=\"pagination-wrapper\">\r\n");
      out.write("                        <a href=\"#\" class=\"button is-medium-button w-button\" id=\"prevPage\" >Previous</a>\r\n");
      out.write("                        <a href=\"#\" class=\"button is-medium-button w-button\" id=\"nextPage\" >Next</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"../js/warehouse-js.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        let curPage = 1\r\n");
      out.write("        let recordsPerPage = 20;\r\n");
      out.write("        let products = onload();\r\n");
      out.write("        document.getElementById(\"prevPage\").addEventListener(\"click\", prevPage);\r\n");
      out.write("        document.getElementById(\"nextPage\").addEventListener(\"click\", nextPage);\r\n");
      out.write("        changePage(1);\r\n");
      out.write("\r\n");
      out.write("        function onload() {\r\n");
      out.write("            return document.getElementById(\"tableBody\").getElementsByTagName(\"tr\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function prevPage() {\r\n");
      out.write("            if (curPage > 1) {\r\n");
      out.write("                curPage--;\r\n");
      out.write("                changePage(curPage);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function nextPage() {\r\n");
      out.write("            if (curPage < numPages()) {\r\n");
      out.write("                curPage++;\r\n");
      out.write("                changePage(curPage);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function changePage(page) {\r\n");
      out.write("            for (let i = 0; i < products.length; i++) {\r\n");
      out.write("                products[i].style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            for (let i = (page - 1) * recordsPerPage; i < products.length && i < (page * recordsPerPage); i++) {\r\n");
      out.write("                products[i].style.display = \"flex\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function numPages() {\r\n");
      out.write("            return Math.ceil(products.length / recordsPerPage);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        window.addEventListener(\"load\", () => {\r\n");
      out.write("            const loader = document.querySelector(\".loader_wrapper\");\r\n");
      out.write("\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                loader.classList.add(\"loader-hidden\");\r\n");
      out.write("\r\n");
      out.write("                loader.addEventListener(\"transitionend\", () => {\r\n");
      out.write("                    document.body.removeChild(loader);\r\n");
      out.write("                });\r\n");
      out.write("            }, 500);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/custom_row_template.css\"/>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row custom-row-footer fs-5\">\r\n");
      out.write("	<div class=\"col-2 mb-3 mt-3\">\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-4 mb-3 mt-3\">\r\n");
      out.write("		<p><strong>Contact us</strong></p>\r\n");
      out.write("		<p><b>Email:</b> support@theshirtstore.com</p>\r\n");
      out.write("		<p><b>Hotline:</b> 0123 465 789</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-3 mb-3 mt-3\">\r\n");
      out.write("		<p><a href=\"about.jsp\" style=\"text-decoration: none; color: #FFFFFF\">About us</a></p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-3 mb-3 mt-3\">\r\n");
      out.write("		<p><b>Policies</b></p>\r\n");
      out.write("		<p><a href=\"privacy_policy.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Privacy Policy</a></p>\r\n");
      out.write("		<p><a href=\"terms.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Terms and Conditions agreement</a></p>\r\n");
      out.write("		<p><a href=\"return_policy.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Return and Refund Policy</a></p>\r\n");
      out.write("		<p><a href=\"disclaimer.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Disclaimer</a></p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row custom-row text-center\">\r\n");
      out.write("	<div class=\"col mb-1 mt-1\">\r\n");
      out.write("		<p><b>Copyright &copy; 2024 by The Shirt Store. All rights reserved.</b></p>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /admin/header.jsp(38,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userRole != 'staff'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"col-2\">\r\n");
          out.write("						<a href=\"list_users\" class=\"btn custom-btn-admin-header\">\r\n");
          out.write("							<img src=\"../images/profile.png\" class=\"logo-size\">\r\n");
          out.write("							<div class=\"mt-2\">Staffs</div>\r\n");
          out.write("						</a>\r\n");
          out.write("					</div>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /admin/header.jsp(105,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userRole != 'staff'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"col-2\">\r\n");
          out.write("						<a href=\"list_promotions\" class=\"btn custom-btn-admin-header\">\r\n");
          out.write("							<img src=\"../images/promotion.png\" class=\"logo-size\">\r\n");
          out.write("							<div class=\"mt-2\">Promotion</div>\r\n");
          out.write("						</a>\r\n");
          out.write("					</div>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/warehouse_list.jsp(60,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("warehouse");
      // /admin/warehouse_list.jsp(60,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/warehouse_list.jsp(60,20) '${warehouseList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${warehouseList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <tr class=\"table_row\">\r\n");
            out.write("                            <td class=\"table_cell align-middle text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                            <td class=\"table_cell align-middle text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                            <td class=\"table_cell align-middle text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                            <td class=\"table_cell align-middle text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.updatedDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                            <td class=\"table_cell align-middle text-center\">\r\n");
            out.write("                                <a href=\"warehouse_detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"button is-medium-button w-button\">View Detail</a>\r\n");
            out.write("                            </td>\r\n");
            out.write("                        </tr>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
